name: Deploy on EC2

on:
  push:
    branches:
      - master
      
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: 35.163.180.116
            USER_NAME: asmoday
        run: | 
          cd ~
          ls
          cat Dockefile
