name: Deploy on EC2

on:
  push:
    branches:
      - master
      
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    steps:
      - name: test
        run: | 
          ls
          echo -n "--------------------------"
          cd ..
          ls
          echo -n "--------------------------"
          cd ..
          ls
          echo -n "--------------------------"
          cd .. 
          ls
          echo -n "--------------------------"
          cd ..
          ls
          echo -n "--------------------------"
          cd ..
          ls
          echo -n "--------------------------"
          cd ..
          ls
